[build]
target-dir = ".rust-target"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "target-cpu=native"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "target-cpu=native",
    "-C",
    "link-arg=-ld_new",
]
