(
  (string
    (string_content) @injection.content
    (#match? @injection.content ".*(SELECT|INSERT|UPDATE|DELETE|MERGE|CALL|CREATE|ALTER|DROP|TRUNCATE|RENAME|GRANT|REVOKE|BEGIN|START|COMMIT|ROLLBACK|SAVEPOINT|SET|USE|DECLARE|PREPARE|EXEC|EXECUTE|WITH|EXPLAIN|PRAGMA|VACUUM|ANALYZE|FETCH|DO|IF|WHILE|FOR|LOOP|SHOW|DESCRIBE|DESC|LOAD|COPY|LOCK|ATTACH|DETACH|RELEASE|ABORT|FAIL).*")
    (#set! injection.language "sql")
  )
)
